version: '3'
services:
  caddy:
    image: yunussandikci/cron-backups
    volumes: #every folder or file you mapped into /backup folder will be backed-up
    - /Users/yunussandikci/Pictures/:/backup/Pictures  
    - /Users/yunussandikci/Downloads/:/backup/Downloads
    - /Users/yunussandikci/Documents/Zoom/:/backup/Zoom
    environment:
      CRON: "* * * * *" #crontab value for backup setting period
      DROPBOX_TOKEN: "<dropbox_token>" #https://www.dropbox.com/developers/apps/create